# Generated by Django 4.2.11 on 2025-02-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='phone_number',
            field=models.BinaryField(null=True),
        ),
    ]
