# Generated by Django 4.2.11 on 2025-02-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_blogpost_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
