# Generated by Django 4.2.11 on 2025-02-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_blogpost_email_alter_blogpost_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
