# Generated by Django 4.2.11 on 2025-02-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_blogpost_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
