# Generated by Django 4.2.11 on 2025-02-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_blogpost_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
